### ISSUE TITLE
Usage help

### ISSUE THREAD

**Issue by getamu** [basis-technology-corp/metrics-cloudwatch-reporter#1]
Hello,
I am getting `package com.basistech.metrics` doesn't exist when I am trying to import it in my file. I have added the mvn dependency and it works fine.
Please help.

**Comment by seth-mg** [comment]
Hi @getamu.
Can you explain your issue in more detail?
You are saying that you've added the dependency to your pom and Maven can fetch it properly but when you `import com.basistech.metrics.CloudWatchReporter;` you get a "package does not exist" error?

**Comment by getamu** [comment]
When I am trying to add the package as dependency and trying to do `import com.basistech.metrics.CloudWatchReporter;` I get a "package does not exist" error?

**Comment by seth-mg** [comment]
Please try reimporting the Maven project in your IDE.  Here are the [reimport instructions for Intellij](https://www.jetbrains.com/help/idea/delegate-build-and-run-actions-to-maven.html#maven_reimport).

I'm also attaching a [small example Maven project](https://github.com/basis-technology-corp/metrics-cloudwatch-reporter/files/4928504/example.zip) that runs from the command line and within Intellij.

Let me know how it goes.
